apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: pvc-grafana
spec:   
    storageClassName: standard 
    accessModes:
      - ReadWriteOnce
    resources:
      requests:   
       storage: "500Mi"
